# コンテナの起動（イメージがない場合には、イメージのビルドも）
# docker-compose up -d
# コンテナへのアクセス
# docker-compose exec （サービス名） sh
# コンテナへのアクセス遮断
# Ctrl + p, Ctrl + q
# コンテナの終了、削除
# docker-compose down
version: '3.1'
services:
  golang: # サービス名
    build: 
      context: .
    # Dockerfileを保存しているパスを指定すれば、自動でイメージをビルドし、コンテナを起動してくれます。
    volumes:
      - "./app:/go/src/app"
    # バインドマウントによりコンテナ内の/go/src/app/とホストマシンの./app/をリンクさせます。
    tty: true
    # コンテナは、本来、特定のコマンドを実行した後に、自ずと終了します。
    # 特定のコマンドを指定しなければ、コンテナは起動と同時に終了しますが、
    # 上記のコマンドを指定すれば、起動したままになります。